# Generated by Django 6.0.6 on 2026-07-07 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('organization_units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='company.company')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organization_units.organizationunit')),
            ],
        ),
    ]
