# Generated by Django 6.0.6 on 2026-07-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0002_alter_useraccount_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
