# Generated by Django 6.0.6 on 2026-07-07 04:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[('division', 'Division'), ('department', 'Department'), ('team', 'Team'), ('branch', 'Branch'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('ownership_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='company.company')),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organization_units.organizationunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
